/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_write.h"

int* transfer_file_1_svc(file* argp, struct svc_req* rqstp)
{
	static int  result;
	FILE* fp;
	fp = fopen("send.txt", "a");
	if (fp == NULL) {
		perror("Cannot read file\n");
		exit(1);
	}

	fwrite(argp->data, 1, argp->data, fp);
	printf("%s \n", argp->data);
	fclose(fp);

	return &result;
}
