/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_write.h"
#include <time.h>

void filestransfer_1(char* host, char* name)
{
	CLIENT* clnt;
	FILE* fp;
	int* result_1;
	file  transfer_file_1_arg;
	char ch;

#ifndef	DEBUG
	clnt = clnt_create(host, FILESTRANSFER, FILESTRANSFER_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */
	clock_t begin = clock();
	strcpy(transfer_file_1_arg.name, name);
	fp = fopen("send.txt", "r");
	if (fp == NULL) {
		perror("Cannot read file\n");
		exit(1);
	}
	else {
		printf("File has been read\n");
	}
	memset(transfer_file_1_arg.data, 0, sizeof(transfer_file_1_arg.data));
	transfer_file_1_arg.data = 0;
	while(1){
		transfer_file_1_arg.data = fread(transfer_file_1_arg.data, 1, 1024, fp);

		result_1 = transfer_file_1(&transfer_file_1_arg, clnt);
		if (result_1 == (int*)NULL) {
			clnt_perror(clnt, "failed to call");
		}
		if(transfer_file_1_arg.buffer_size < 1024) {
			printf("\nUpload done!\n");
			break;
		}
	}
	clock_t end = clock();
	double upload_time = (double)(end - begin) / CLOCKS_PER_SEC;

	printf("Upload time: %lf\n", upload_time);
	printf("File has been sent\n");



#ifndef	DEBUG
	clnt_destroy(clnt);
#endif	 /* DEBUG */
	fclose(fp);
}


int main(int argc, char* argv[])
{
	char* host;
	char* name;

	if (argc < 3) {
		printf("used: %s server_host file_name\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	filename = argv[2];
	filestransfer_1(host, name);
	exit(0);
}