/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

struct file {
	char name[1024];
	char data[1024];
};
typedef struct file file;

#define FILESTRANSFER 0x43521111 
#define FILESTRANSFER_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define transfer_file 1
extern  int * transfer_file_1(file *, CLIENT *);
extern  int * transfer_file_1_svc(file *, struct svc_req *);
extern int filestransfer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define transfer_file 1
extern  int * transfer_file_1();
extern  int * transfer_file_1_svc();
extern int filestransfer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file (XDR *, file*);

#else /* K&R C */
extern bool_t xdr_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
